# Generated by Django 4.2.1 on 2023-05-20 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AddField(
            model_name='client',
            name='e_mail',
            field=models.CharField(blank=True, db_column='Электронная почта', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='middle_name',
            field=models.CharField(blank=True, db_column='Отчество', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='name',
            field=models.CharField(blank=True, db_column='Имя', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='password',
            field=models.CharField(blank=True, db_column='Пароль', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='phone_number',
            field=models.CharField(blank=True, db_column='Номер телефона', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='surname',
            field=models.CharField(blank=True, db_column='Фамилия', max_length=50, null=True),
        ),
    ]
