# Generated by Django 4.2.1 on 2023-05-21 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='e_mail',
        ),
        migrations.RemoveField(
            model_name='client',
            name='name',
        ),
        migrations.RemoveField(
            model_name='client',
            name='password',
        ),
        migrations.RemoveField(
            model_name='client',
            name='surname',
        ),
    ]
