# Generated by Django 4.2.1 on 2023-05-20 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_client_e_mail_alter_client_middle_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='e_mail',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Электронная почта'),
        ),
    ]
