# Generated by Django 4.2.1 on 2023-05-20 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_data',
            field=models.BinaryField(blank=True, null=True, verbose_name='Данные'),
        ),
        migrations.AlterField(
            model_name='file',
            name='file_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Имя'),
        ),
    ]
