# Generated by Django 4.2.1 on 2023-05-22 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0006_remove_platform_photo'),
        ('main', '0002_remove_file_file_data_remove_file_file_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformPhotoAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(upload_to='', verbose_name='Фотография')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='platforms.platform')),
            ],
            options={
                'verbose_name': 'Фотографии площадок',
                'verbose_name_plural': 'Фотография площадки',
            },
        ),
    ]
