# Generated by Django 4.2.1 on 2023-05-20 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_file_file_data_alter_file_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_name',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Имя'),
        ),
    ]
