# Generated by Django 4.2.1 on 2023-05-22 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0006_remove_platform_photo'),
        ('main', '0003_platformphotoattachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='', verbose_name='Файл')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='platforms.platform')),
            ],
            options={
                'verbose_name': 'Закреплённые файлы площадок',
                'verbose_name_plural': 'Закреплённый файл площадки',
            },
        ),
        migrations.DeleteModel(
            name='PlatformPhotoAttachment',
        ),
    ]
