# Generated by Django 4.2.1 on 2023-05-22 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_platformattachment_delete_platformphotoattachment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='platformattachment',
            options={'verbose_name': 'Закреплённый файл площадки', 'verbose_name_plural': 'Закреплённые файлы площадок'},
        ),
    ]
