# Generated by Django 4.2.1 on 2023-05-23 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_platformattachment_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=256, verbose_name='E-mail')),
            ],
            options={
                'verbose_name': 'Не подтверждённый e-mail',
                'verbose_name_plural': 'Не подтверждённые e-mail',
            },
        ),
    ]
