# Generated by Django 4.2.1 on 2023-05-23 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0014_remove_comment_attachment'),
        ('main', '0009_alter_emailverification_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='', verbose_name='Файл')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='platforms.comment')),
            ],
            options={
                'verbose_name': 'Закреплённый файл отзыва',
                'verbose_name_plural': 'Закреплённые файлы отзывов',
            },
        ),
        migrations.DeleteModel(
            name='File',
        ),
    ]
