# Generated by Django 4.2.1 on 2023-05-24 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_commentattachment_delete_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='email',
            field=models.CharField(blank=True, max_length=250, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='emailverification',
            name='first_name',
            field=models.CharField(blank=True, max_length=250, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='emailverification',
            name='last_name',
            field=models.CharField(blank=True, max_length=250, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='emailverification',
            name='password',
            field=models.CharField(blank=True, max_length=250, verbose_name='Пароль'),
        ),
        migrations.AlterField(
            model_name='emailverification',
            name='verification_code',
            field=models.CharField(max_length=250, null=True, unique=True, verbose_name='Код подтверждения'),
        ),
    ]
