# Generated by Django 4.2.1 on 2023-05-27 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_emailverification_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordReset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=250, verbose_name='E-mail')),
                ('verification_code', models.CharField(max_length=250, null=True, unique=True, verbose_name='Код подтверждения')),
            ],
            options={
                'verbose_name': 'Пароль для сброса',
                'verbose_name_plural': 'Пароли для сброса',
            },
        ),
    ]
