# Generated by Django 4.2.1 on 2023-05-20 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AlterModelOptions(
            name='freeslot',
            options={'verbose_name': 'Свободный слот', 'verbose_name_plural': 'Свободные слоты'},
        ),
        migrations.AlterModelOptions(
            name='platform',
            options={'verbose_name': 'Площадка', 'verbose_name_plural': 'Площадки'},
        ),
        migrations.AddField(
            model_name='comment',
            name='rating',
            field=models.FloatField(blank=True, null=True, verbose_name='Рейтинг'),
        ),
        migrations.AddField(
            model_name='comment',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст отзыва'),
        ),
        migrations.AddField(
            model_name='freeslot',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Свободная дата'),
        ),
        migrations.AddField(
            model_name='platform',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание площадки'),
        ),
        migrations.AddField(
            model_name='platform',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='platform',
            name='rating',
            field=models.FloatField(blank=True, null=True, verbose_name='Рейтинг'),
        ),
        migrations.AddField(
            model_name='platform',
            name='schedule',
            field=models.JSONField(blank=True, null=True, verbose_name='Расписание'),
        ),
    ]
