# Generated by Django 4.2.1 on 2023-05-20 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizers', '0006_entry_client'),
        ('platforms', '0002_alter_comment_options_alter_freeslot_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='organizer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizers.organizer'),
        ),
    ]
