# Generated by Django 4.2.1 on 2023-05-22 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0002_alter_platform_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
