# Generated by Django 4.2.1 on 2023-05-20 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0003_platform_organizer'),
    ]

    operations = [
        migrations.AddField(
            model_name='freeslot',
            name='platform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='platforms.platform'),
        ),
    ]
