# Generated by Django 4.2.1 on 2023-05-20 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_alter_client_e_mail'),
        ('platforms', '0004_freeslot_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.client'),
        ),
        migrations.AddField(
            model_name='comment',
            name='platform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='platforms.platform'),
        ),
    ]
