# Generated by Django 4.2.1 on 2023-05-22 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_file_file_data_remove_file_file_name_and_more'),
        ('platforms', '0004_alter_platform_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='photo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_photo', to='main.file'),
        ),
    ]
