# Generated by Django 4.2.1 on 2023-05-22 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0005_alter_platform_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platform',
            name='photo',
        ),
    ]
