# Generated by Django 4.2.1 on 2023-05-22 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0006_remove_platform_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='agreement',
            field=models.FileField(null=True, upload_to='', verbose_name='Соглашение'),
        ),
    ]
