# Generated by Django 4.2.1 on 2023-05-20 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_file_file_name'),
        ('platforms', '0006_comment_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.file'),
        ),
    ]
