# Generated by Django 4.2.1 on 2023-05-20 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_file_file_name'),
        ('platforms', '0007_platform_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='agreement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_agreement', to='main.file'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photo_agreement', to='main.file'),
        ),
    ]
