# Generated by Django 4.2.1 on 2023-05-22 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0007_alter_platform_agreement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='agreement',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Соглашение'),
        ),
    ]
