# Generated by Django 4.2.1 on 2023-05-23 21:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0010_alter_platform_agreement'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='category',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name='Категория'),
            preserve_default=False,
        ),
    ]
