# Generated by Django 4.2.1 on 2023-05-23 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0012_freeslot_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='short_description',
            field=models.TextField(blank=True, verbose_name='Краткое описание'),
        ),
    ]
