# Generated by Django 4.2.1 on 2023-05-23 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0013_platform_short_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='attachment',
        ),
    ]
