# Generated by Django 4.2.1 on 2023-05-24 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0014_remove_comment_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='rating',
            field=models.FloatField(blank=True, verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='freeslot',
            name='date',
            field=models.DateField(blank=True, verbose_name='Свободная дата'),
        ),
        migrations.AlterField(
            model_name='freeslot',
            name='price',
            field=models.IntegerField(blank=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='category',
            field=models.CharField(blank=True, max_length=250, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='name',
            field=models.CharField(blank=True, max_length=250, verbose_name='Имя'),
        ),
    ]
