# Generated by Django 4.2.1 on 2023-05-25 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0016_remove_platform_category_platform_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='rating',
            field=models.FloatField(blank=True, verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='schedule',
            field=models.JSONField(blank=True, null=True, verbose_name='Расписание'),
        ),
    ]
