# Generated by Django 4.2.1 on 2023-05-26 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0017_alter_platform_rating_alter_platform_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='address',
            field=models.JSONField(blank=True, null=True, verbose_name='Адрес'),
        ),
    ]
