# Generated by Django 4.2.1 on 2023-05-26 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0018_platform_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='verified',
            field=models.BooleanField(default=False, verbose_name='Подтверждена'),
        ),
    ]
