# Generated by Django 4.2.1 on 2023-05-28 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0019_platform_verified'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FreeSlot',
        ),
    ]
