# Generated by Django 4.2.1 on 2023-05-28 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0020_delete_freeslot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platform',
            name='categories',
        ),
        migrations.AddField(
            model_name='platform',
            name='category',
            field=models.CharField(blank=True, max_length=250, verbose_name='Категория'),
        ),
    ]
