# Generated by Django 4.2.1 on 2023-05-20 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_alter_client_e_mail'),
        ('organizers', '0002_alter_entry_options_alter_organizer_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.client'),
        ),
    ]
