# Generated by Django 4.2.1 on 2023-05-20 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0002_alter_comment_options_alter_freeslot_options_and_more'),
        ('organizers', '0003_entry_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='platform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='platforms.platform'),
        ),
    ]
