# Generated by Django 4.2.1 on 2023-05-21 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizers', '0004_organizer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizer',
            name='e_mail',
        ),
        migrations.RemoveField(
            model_name='organizer',
            name='name',
        ),
        migrations.RemoveField(
            model_name='organizer',
            name='password',
        ),
        migrations.RemoveField(
            model_name='organizer',
            name='surname',
        ),
    ]
