# Generated by Django 4.2.1 on 2023-05-22 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizers', '0005_remove_organizer_e_mail_remove_organizer_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizer',
            name='phone_number',
            field=models.CharField(max_length=50, verbose_name='Номер телефона'),
        ),
    ]
