# Generated by Django 4.2.1 on 2023-05-23 21:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('organizers', '0007_organizer_email_verification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='date',
        ),
        migrations.AddField(
            model_name='entry',
            name='date_end',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата окончания записи'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entry',
            name='date_start',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата начала записи'),
            preserve_default=False,
        ),
    ]
