# Generated by Django 4.2.1 on 2023-05-24 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0011_alter_emailverification_email_and_more'),
        ('organizers', '0008_remove_entry_date_entry_date_end_entry_date_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='date_end',
            field=models.DateTimeField(blank=True, verbose_name='Дата окончания записи'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='date_start',
            field=models.DateTimeField(blank=True, verbose_name='Дата начала записи'),
        ),
        migrations.AlterField(
            model_name='organizer',
            name='email_verification',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.emailverification'),
        ),
        migrations.AlterField(
            model_name='organizer',
            name='inn',
            field=models.CharField(blank=True, max_length=250, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='organizer',
            name='juridical_name',
            field=models.CharField(blank=True, max_length=250, verbose_name='Юридическое лицо'),
        ),
        migrations.AlterField(
            model_name='organizer',
            name='middle_name',
            field=models.CharField(blank=True, max_length=250, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='organizer',
            name='phone_number',
            field=models.CharField(blank=True, max_length=250, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='organizer',
            name='position',
            field=models.CharField(blank=True, max_length=250, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='organizer',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
