# Generated by Django 4.2.1 on 2023-05-24 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizers', '0009_alter_entry_date_end_alter_entry_date_start_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='date_start',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='date_end',
        ),
    ]
