# Generated by Django 4.2.1 on 2023-05-28 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_alter_client_email_verification_and_more'),
        ('organizers', '0010_rename_date_start_entry_date_remove_entry_date_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='price',
            field=models.IntegerField(default=1000, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.client'),
        ),
    ]
