# Generated by Django 4.2.1 on 2023-05-28 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizers', '0011_entry_price_alter_entry_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='date',
            field=models.DateField(blank=True, verbose_name='Дата начала записи'),
        ),
    ]
